import Link from "next/link";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { getProductStockByLocation, getRecentStockMovements, getTotalStockForProduct } from "@/lib/inventory/queries";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function ProductDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const product = await db.product.findUnique({ where: { id }, include: { category: true } });
  if (!product) notFound();
  const [totalStock, balances, movements] = await Promise.all([getTotalStockForProduct(id), getProductStockByLocation(id), getRecentStockMovements({ productId: id, limit: 10 })]);
  const reorderLevel = Number(product.reorderLevel);
  const isLowStock = totalStock <= reorderLevel;
  return <div className="space-y-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/products" className="text-sm text-slate-500 hover:text-slate-900">← Products</Link><div className="mt-3 flex items-center gap-3"><h1 className="text-3xl font-semibold tracking-tight">{product.name}</h1>{isLowStock ? <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-700">Low stock</span> : null}</div><p className="mt-2 text-sm text-slate-500">{product.sku} · {product.category.name}</p></div><Button asChild variant="outline"><Link href={`/products/${id}/edit`}>Edit product</Link></Button></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border bg-white p-5"><p className="text-sm text-slate-500">Total stock</p><p className="mt-3 text-3xl font-semibold">{totalStock}</p><p className="mt-1 text-xs text-slate-400">{product.unitOfMeasure}</p></div><div className="rounded-lg border bg-white p-5"><p className="text-sm text-slate-500">Reorder threshold</p><p className="mt-3 text-3xl font-semibold">{reorderLevel}</p><p className="mt-1 text-xs text-slate-400">{isLowStock ? "Replenishment needed" : "Above threshold"}</p></div><div className="rounded-lg border bg-white p-5"><p className="text-sm text-slate-500">Category</p><p className="mt-3 text-lg font-semibold">{product.category.name}</p><p className="mt-1 text-xs text-slate-400">Unit: {product.unitOfMeasure}</p></div></div><section className="rounded-lg border bg-white"><div className="border-b px-5 py-4"><h2 className="font-semibold">Stock by location</h2></div><div className="divide-y">{balances.map((balance) => <div key={balance.id} className="flex items-center justify-between px-5 py-4 text-sm"><div><p className="font-medium text-slate-800">{balance.location.name}</p><p className="text-xs text-slate-500">{balance.location.warehouse.name}</p></div><p className="font-semibold">{balance.quantity} {product.unitOfMeasure}</p></div>)}{balances.length === 0 ? <p className="p-5 text-sm text-slate-500">No stock has been recorded at a location yet.</p> : null}</div></section><section className="rounded-lg border bg-white"><div className="border-b px-5 py-4"><h2 className="font-semibold">Recent stock movements</h2></div><div className="divide-y">{movements.map((movement) => <div key={movement.id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4 text-sm"><div><p className="font-medium text-slate-800">{movement.movementType}</p><p className="text-xs text-slate-500">{movement.fromLocation?.name ?? "External"} → {movement.toLocation?.name ?? "External"} · {movement.createdAt.toLocaleDateString()}</p></div><p className="font-semibold">{movement.quantity} {product.unitOfMeasure}</p></div>)}{movements.length === 0 ? <p className="p-5 text-sm text-slate-500">No movements recorded yet.</p> : null}</div></section></div>;
}
